# Generated by Django 4.2.5 on 2023-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EasyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant_Name', models.CharField(max_length=50)),
                ('Submission_Time', models.DateTimeField(auto_now_add=True)),
                ('Score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HardLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant_Name', models.CharField(max_length=50)),
                ('Submission_Time', models.DateTimeField(auto_now_add=True)),
                ('Score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MediumLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant_Name', models.CharField(max_length=50)),
                ('Submission_Time', models.DateTimeField(auto_now_add=True)),
                ('Score', models.IntegerField()),
            ],
        ),
    ]
