# Generated by Django 4.2.5 on 2023-10-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easylevel',
            name='Submission_Time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hardlevel',
            name='Submission_Time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mediumlevel',
            name='Submission_Time',
            field=models.DateTimeField(),
        ),
    ]
